//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsZone
{
    using System;
    using System.Collections.Generic;
    
    public partial class matches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public matches()
        {
            this.match_result = new HashSet<match_result>();
        }
    
        public int mid { get; set; }
        public int club1 { get; set; }
        public int club2 { get; set; }
        public int gameid { get; set; }
        public string loc { get; set; }
        public System.DateTime C_date { get; set; }
        public Nullable<bool> C_status { get; set; }
        public string ov { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<match_result> match_result { get; set; }
        public virtual clubs clubs { get; set; }
        public virtual clubs clubs1 { get; set; }
        public virtual games games { get; set; }
    }
}
