//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsZone
{
    using System;
    using System.Collections.Generic;
    
    public partial class players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public players()
        {
            this.player_associations = new HashSet<player_associations>();
            this.player_associations_request = new HashSet<player_associations_request>();
        }
    
        public int playerid { get; set; }
        public int userid { get; set; }
        public string playername { get; set; }
        public Nullable<int> age { get; set; }
        public string photo { get; set; }
        public string cover { get; set; }
        public Nullable<double> height { get; set; }
        public string bio { get; set; }
        public int roleid { get; set; }
    
        public virtual games_positions games_positions { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player_associations> player_associations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player_associations_request> player_associations_request { get; set; }
    }
}
